- hosts: etcd_nodes
  become: yes
  roles:
  - role: etcd_node
  pre_tasks:
  - name: Temp override for "hostname_fqdn"
    set_fact:
      hostname_fqdn  : "{{ inventory_hostname }}"
    when: hostname_fqdn is not defined

  # provisioned machine might have incorrect hostname if thats the case override facts to new name
  - name: Temp override facts "ansible_fqdn"
    set_fact:
      ansible_fqdn : "{{ inventory_hostname }}"
    when: ansible_fqdn != inventory_hostname

  - name: Temp override facts "hostname_short"
    set_fact:
      ansible_hostname  : "{{ inventory_hostname_short }}"
    when: ansible_hostname != inventory_hostname_short

