- name: Create service file
  copy:
    src: etcd.service
    dest: /usr/lib/systemd/system/etcd.service
  register: create_service
- name: Reload service file
  command: systemctl daemon-reload
  when: create_service.changed
- name: Ensure etcd service is running
  service: name=etcd state=started
