- name: Create conf directory
  file: path=/etc/etcd state=directory
- name: Set ownership of etcd key
  file:
    path: "{{ etcd_private_key }}"
    owner: "{{ etcd_user }}"
  when: etcd_ssl_enabled
- name: Create lib directory
  file:
    path: /var/lib/etcd
    state: directory
    owner: "{{ etcd_user }}"
    group: "{{ etcd_user }}"
    mode: 0700
- name: Create configuration file
  template:
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf
  tags: etcd-config
