- name: Ensure etcd group exists
  group:
    name: "{{ etcd_user }}"
    system: yes
    state: present
- name: Ensure etcd user exists
  user:
    name: "{{ etcd_user }}"
    group: "{{ etcd_user }}"
    home: /var/lib/etcd
    system: yes
