- name: Pull etcd image
  docker_image: name={{ etcd_image_name }} tag={{ etcd_image_version }}
- name: Install etcd pod
  template: src=etcd.json.j2 dest=/etc/kubernetes/manifests/etcd.json
- name: Wait for etcd to start - 30 seconds
  wait_for: host={{ etcd_client_local_ip }} port=2379 timeout=30
