- name: Configure etcd YUM repository
  when: not sensu_embedded_etcd
  yum_repository:
    name: etcd
    description: etcd
    baseurl: "{{ etcd_yum_repo_url }}"
    gpgcheck: no
- name: Ensure etcd is installed and up to date
  package:
    name: etcd-{{ etcd_version }}
    state: present
- include_tasks: configure-etcd-service.yml
  when: not sensu_embedded_etcd and etcd_enable_service
