- name: Include fact tasks
  include_tasks: gather-facts.yml

- name: Include tasks for existing cluster members
  include_tasks: existing-member-tasks.yml
  when: etcd_already_in_cluster

- name: Include tasks for new cluster members
  include_tasks: new-member-tasks.yml
  when: etcd_cluster_exists and not etcd_already_in_cluster

- name: Create user
  when: not sensu_embedded_etcd and etcd_user != 'root'
  block:
  - name: Ensure etcd group exists
    group:
      name: "{{ etcd_user }}"
      system: yes
      state: present
  - name: Ensure etcd user exists
    user:
      name: "{{ etcd_user }}"
      group: "{{ etcd_user }}"
      home: /var/lib/etcd
      system: yes
- name: Create conf directory
  when: not sensu_embedded_etcd 
  file:
    path: /etc/etcd
    state: directory
- name: Set ownership of etcd key
  when: not sensu_embedded_etcd 
  file:
    path: "{{ etcd_private_key }}"
    owner: "{{ etcd_user }}"
  when: etcd_ssl_enabled | bool
- name: Create lib directory
  when: not sensu_embedded_etcd 
  file:
    path: /var/lib/etcd
    state: directory
    owner: "{{ etcd_user }}"
    group: "{{ etcd_user }}"
    mode: 0700
- name: Create configuration file
  when: not sensu_embedded_etcd 
  template:
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf
  vars:
    etcd_initial_cluster_state: "{{ 'existing' if etcd_cluster_exists and not etcd_already_in_cluster else 'new' }}"

- include_tasks: install-etcd-{{ etcd_install_mode }}.yml

- name: Wait for etcd to start - 30 seconds
  when: etcd_enable_service
  wait_for: host={{ etcd_client_listen_ip }} port=2379 timeout=30

- name: Check health
  when: etcd_enable_service
  uri:
    url: "{{ etcd_protocol }}://{{ etcd_client_listen_ip }}:2379/health"
    client_cert: "{{ etcd_cert }}"
    client_key: "{{ etcd_private_key }}"
    validate_certs: no
