- set_fact: etcd_hostname={{ etcd_hostname }}
  tags: always
- include: install-etcd.yml
  tags: install-etcd
- include: generate-certs.yml
  when: etcd_ssl_enabled
  tags: generate-certs
- include: configure-services.yml
  tags: configure-services
