- name: Set etcd_peer_listen_ip fact
  set_fact:
    etcd_peer_listen_ip: "{{ etcd_peer_listen_ip }}"
- name: Create user
  when: etcd_user != 'root'
  block:
  - name: Ensure etcd group exists
    group:
      name: "{{ etcd_user }}"
      system: yes
      state: present
  - name: Ensure etcd user exists
    user:
      name: "{{ etcd_user }}"
      group: "{{ etcd_user }}"
      home: /var/lib/etcd
      system: yes
- name: Create conf directory
  file:
    path: /etc/etcd
    state: directory
- name: Set ownership of etcd key
  file:
    path: "{{ etcd_private_key }}"
    owner: "{{ etcd_user }}"
  when: etcd_ssl_enabled | bool
- name: Create lib directory
  file:
    path: /var/lib/etcd
    state: directory
    owner: "{{ etcd_user }}"
    group: "{{ etcd_user }}"
    mode: 0700
- name: Create configuration file
  template:
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf

- include_tasks: install-etcd-{{ etcd_install_mode }}.yml

- name: Wait for etcd to start - 30 seconds
  wait_for: host={{ etcd_client_listen_ip }} port=2379 timeout=30
