- set_fact: etcd_hostname={{ etcd_hostname }}
  tags: always
- include: create-user.yml
  when: etcd_user != 'root'
- include: configure-etcd.yml
  tags: configure-etcd
- include: "{{ 'install-etcd-pod.yml' if etcd_pod_install else 'install-etcd-local.yml' }}"
  tags: install-etcd
- name: Wait for etcd to start - 30 seconds
  wait_for: host={{ etcd_client_listen_ip }} port=2379 timeout=30
